version: 2

sources:
  - name: raw_data  
    schema: landing  
    tables:
      - name: Retail_sales


models:
  - name: int_retail_sales
    columns:
      - name: ITEM_TYPE
        tests:
          - not_null

      - name: SUPPLIER
        tests:
          - not_null 

      - name: RETAIL_SALES 
        tests: 
          - not_null

